# Generated by Django 4.1.3 on 2022-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='Email',
            field=models.EmailField(default='de2', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Password',
            field=models.CharField(default='de2', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='Name',
            field=models.CharField(default='de2', max_length=75),
        ),
        migrations.AddField(
            model_name='staff',
            name='Staff_id',
            field=models.AutoField(default='de2', primary_key=True, serialize=False),
        ),
    ]
