# Generated by Django 4.1.3 on 2022-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField(max_length=500, unique=True)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('Correct_Ans', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('Score_id', models.AutoField(primary_key=True, serialize=False)),
                ('Score', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='Course_id',
            field=models.AutoField(default='any', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='course',
            name='Name',
            field=models.CharField(default='Haha', max_length=250, unique=True),
        ),
    ]
