# Generated by Django 4.1.3 on 2022-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default='de2', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='de2', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='de2', max_length=75),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(default='de2', primary_key=True, serialize=False),
        ),
    ]
